name: Ejecutar Python

on:
  push:
    branches: [ main ]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Ejecutar hola.py
      run: python hola.py
